"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { fallbackExpenseCategoryDefinitions, initialMetaAdsTaxConfiguration, syncExpenseCategoryDefinitions, type Expense, type ExpenseCategory, type ExpenseCategoryDefinition, type ExpenseInput, type ExpenseTaxItem } from "@/data/expense-types";
import type { AdAccount, Campaign } from "@/data/campaign-types";
import {
  TaxAwareExpenseDrawer,
  ExpenseFilters,
  ExpenseInsights,
  ExpenseSetupNotice,
  PremiumExpenseTable,
  FinanceHeader,
  FinanceMetrics,
  DeleteExpenseDialog,
  ProductMessage
} from "@/modules/finance/components/expense-workspace";

const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => `${today().slice(0, 7)}-01`;

const emptyForm: ExpenseInput = {
  description: "",
  category: "traffic",
  amount: "",
  expenseDate: today(),
  source: "Meta Ads",
  notes: "",
  taxCalculationMode: "on_top",
  taxItems: initialMetaAdsTaxConfiguration.map((item) => ({ ...item, calculationBase: 0, amount: 0, calculationMode: "on_top", isAutoGenerated: true, enabled: true }))
};

function expenseTaxes(expense: Expense) {
  return (expense.taxItems || []).reduce((sum, item) => sum + item.amount, 0);
}

async function readJson(response: Response) {
  const text = await response.text();
  if (!text) return {};
  try {
    return JSON.parse(text) as Record<string, unknown>;
  } catch {
    return { error: "O servidor retornou uma resposta inválida." };
  }
}

function inclusiveDays(start: string, end: string) {
  const startTime = new Date(`${start}T12:00:00Z`).getTime();
  const endTime = new Date(`${end}T12:00:00Z`).getTime();
  if (!Number.isFinite(startTime) || !Number.isFinite(endTime) || endTime < startTime) return 1;
  return Math.floor((endTime - startTime) / 86400000) + 1;
}

export function ExpensesScreen() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [startDate, setStartDate] = useState(monthStart());
  const [endDate, setEndDate] = useState(today());
  const [category, setCategory] = useState<ExpenseCategory | "all">("all");
  const [source, setSource] = useState("all");
  const [search, setSearch] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [setupRequired, setSetupRequired] = useState(false);
  const [taxSetupRequired, setTaxSetupRequired] = useState(false);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [form, setForm] = useState<ExpenseInput>(emptyForm);
  const [editing, setEditing] = useState<Expense | null>(null);
  const [deleting, setDeleting] = useState<Expense | null>(null);
  const [drawerInitial, setDrawerInitial] = useState("");
  const [categories, setCategories] = useState<ExpenseCategoryDefinition[]>(fallbackExpenseCategoryDefinitions);
  const [isCategoryOpen, setIsCategoryOpen] = useState(false);
  const [categoryName, setCategoryName] = useState("");
  const [categoryError, setCategoryError] = useState<string | null>(null);
  const [adAccounts, setAdAccounts] = useState<AdAccount[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [expenseAccountId, setExpenseAccountId] = useState("");

  useEffect(() => {
    let active = true;
    fetch("/api/expense-categories", { cache: "no-store", credentials: "include" }).then(readJson).then((payload) => {
      if (!active || !Array.isArray(payload.categories)) return;
      const loaded = payload.categories as ExpenseCategoryDefinition[];
      setCategories(loaded);
      syncExpenseCategoryDefinitions(loaded);
    }).catch(() => undefined);
    return () => { active = false; };
  }, []);

  useEffect(() => {
    fetch("/api/campaigns?status=active", { cache: "no-store", credentials: "include" }).then(readJson).then((payload) => {
      setAdAccounts(Array.isArray(payload.accounts) ? payload.accounts as AdAccount[] : []);
      setCampaigns(Array.isArray(payload.campaigns) ? payload.campaigns as Campaign[] : []);
    }).catch(() => undefined);
  }, []);

  const loadExpenses = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ start: startDate, end: endDate });
      if (category !== "all") params.set("category", category);
      const response = await fetch(`/api/expenses?${params}`, { cache: "no-store", credentials: "include" });
      const payload = await readJson(response);
      if (!response.ok) throw new Error(String(payload.error || "Não foi possível carregar as despesas."));
      setExpenses(Array.isArray(payload.expenses) ? payload.expenses as Expense[] : []);
      setSetupRequired(Boolean(payload.setupRequired));
      setTaxSetupRequired(Boolean(payload.taxSetupRequired));
    } catch (loadError) {
      setExpenses([]);
      setError(loadError instanceof Error ? loadError.message : "Não foi possível carregar as despesas.");
    } finally {
      setIsLoading(false);
    }
  }, [startDate, endDate, category]);

  useEffect(() => { loadExpenses(); }, [loadExpenses]);
  useEffect(() => {
    if (!success) return;
    const timeout = window.setTimeout(() => setSuccess(null), 3500);
    return () => window.clearTimeout(timeout);
  }, [success]);

  const sourceOptions = useMemo(() => Array.from(new Set(expenses.map((item) => item.source).filter((item): item is string => Boolean(item)))).sort(), [expenses]);
  const visibleExpenses = useMemo(() => {
    const term = search.trim().toLocaleLowerCase("pt-BR");
    return expenses.filter((item) => {
      if (source !== "all" && item.source !== source) return false;
      if (term && !item.description.toLocaleLowerCase("pt-BR").includes(term)) return false;
      return true;
    });
  }, [expenses, search, source]);

  const totals = useMemo(() => {
    const total = visibleExpenses.reduce((sum, item) => sum + item.amount + expenseTaxes(item), 0);
    const traffic = visibleExpenses.filter((item) => item.category === "traffic").reduce((sum, item) => sum + item.amount, 0);
    const taxes = visibleExpenses.reduce((sum, item) => sum + expenseTaxes(item), 0);
    return { total, traffic, taxes, count: visibleExpenses.length, dailyAverage: total / inclusiveDays(startDate, endDate) };
  }, [visibleExpenses, startDate, endDate]);

  const filtersChanged = startDate !== monthStart() || endDate !== today() || category !== "all" || source !== "all" || Boolean(search.trim());
  const periodLabel = `${new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${startDate}T12:00:00Z`))} — ${new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${endDate}T12:00:00Z`))}`;

  function clearFilters() {
    setStartDate(monthStart());
    setEndDate(today());
    setCategory("all");
    setSource("all");
    setSearch("");
  }

  function openCreate() {
    syncExpenseCategoryDefinitions(categories);
    setEditing(null);
    const nextForm = { ...emptyForm, expenseDate: today(), taxItems: emptyForm.taxItems?.map((item) => ({ ...item })) };
    setForm(nextForm);
    setDrawerInitial(JSON.stringify(nextForm));
    setIsFormOpen(true);
    setExpenseAccountId("");
  }

  function openEdit(expense: Expense) {
    syncExpenseCategoryDefinitions(categories.map((item) => item.slug === expense.category ? { ...item, isActive: true } : item));
    setEditing(expense);
    const linkedTaxes = expense.taxItems || [];
    const mode = linkedTaxes[0]?.calculationMode || "on_top";
    const configuredTaxes: ExpenseTaxItem[] = initialMetaAdsTaxConfiguration.map((initial) => {
      const saved = linkedTaxes.find((item) => item.taxCode === initial.taxCode);
      return saved ? { ...saved, enabled: true } : { ...initial, calculationBase: expense.amount, amount: 0, calculationMode: mode, isAutoGenerated: true, enabled: false };
    });
    const displayedAmount = mode === "included" ? expense.amount + linkedTaxes.reduce((sum, item) => sum + item.amount, 0) : expense.amount;
    const nextForm = { description: expense.description, category: expense.category, amount: String(displayedAmount), expenseDate: expense.expenseDate, source: expense.source || "", notes: expense.notes || "", campaignId: expense.campaignId || undefined, taxCalculationMode: mode, taxItems: configuredTaxes } satisfies ExpenseInput;
    setForm(nextForm);
    setDrawerInitial(JSON.stringify(nextForm));
    setIsFormOpen(true);
    setExpenseAccountId(campaigns.find((item) => item.id === expense.campaignId)?.adAccountId || "");
  }

  function closeDrawer() {
    const dirty = JSON.stringify(form) !== drawerInitial;
    if (dirty && !window.confirm("Descartar as alterações desta despesa?")) return;
    setIsFormOpen(false);
    setEditing(null);
  }

  async function saveExpense(event: FormEvent) {
    event.preventDefault();
    setIsSaving(true);
    setError(null);
    try {
      const isMetaAds = form.category === "traffic" && form.source === "Meta Ads";
      const enabledTaxes = isMetaAds ? (form.taxItems || []).filter((item) => item.enabled !== false) : [];
      const enteredAmount = Number(String(form.amount).replace(",", "."));
      const rateTotal = enabledTaxes.reduce((sum, item) => sum + Number(item.ratePercent || 0), 0);
      const mediaAmount = form.taxCalculationMode === "included" ? enteredAmount / (1 + rateTotal / 100) : enteredAmount;
      const requestPayload = {
        ...form,
        amount: Math.round(mediaAmount * 100) / 100,
        taxItems: enabledTaxes.map((item) => ({ ...item, calculationBase: mediaAmount, amount: mediaAmount * (item.ratePercent / 100), calculationMode: form.taxCalculationMode || "on_top" }))
      };
      const response = await fetch(editing ? `/api/expenses?id=${editing.id}` : "/api/expenses", {
        method: editing ? "PATCH" : "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(requestPayload)
      });
      const responsePayload = await readJson(response);
      if (!response.ok) throw new Error(String(responsePayload.error || "Não foi possível salvar a despesa."));
      setIsFormOpen(false);
      setEditing(null);
      setSuccess(editing ? "Despesa atualizada com sucesso." : "Despesa registrada com sucesso.");
      await loadExpenses();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Não foi possível salvar a despesa.");
    } finally {
      setIsSaving(false);
    }
  }

  async function deleteExpense() {
    if (!deleting) return;
    setIsSaving(true);
    setError(null);
    try {
      const response = await fetch(`/api/expenses?id=${deleting.id}`, { method: "DELETE", credentials: "include" });
      const payload = await readJson(response);
      if (!response.ok) throw new Error(String(payload.error || "Não foi possível excluir a despesa."));
      setDeleting(null);
      setSuccess("Despesa excluída com sucesso.");
      await loadExpenses();
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : "Não foi possível excluir a despesa.");
    } finally {
      setIsSaving(false);
    }
  }


  async function createCategory(event: FormEvent) {
    event.preventDefault();
    setIsSaving(true);
    setCategoryError(null);
    try {
      const response = await fetch("/api/expense-categories", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ name: categoryName }) });
      const payload = await readJson(response);
      if (!response.ok) throw new Error(String(payload.error || "Não foi possível criar a categoria."));
      const created = payload.category as ExpenseCategoryDefinition;
      const next = [...categories, created].sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));
      setCategories(next);
      syncExpenseCategoryDefinitions(next);
      setForm((current) => ({ ...current, category: created.slug }));
      setCategoryName("");
      setIsCategoryOpen(false);
    } catch (creationError) {
      setCategoryError(creationError instanceof Error ? creationError.message : "Não foi possível criar a categoria.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="space-y-4 pb-10 pt-2">
      <FinanceHeader periodLabel={periodLabel} setupRequired={setupRequired} onCreate={openCreate} />
      {setupRequired ? <ExpenseSetupNotice /> : null}
      {taxSetupRequired ? <ProductMessage tone="error" message="A migration 023 precisa ser aplicada para ativar os tributos automáticos da Meta Ads." /> : null}
      {error ? <ProductMessage tone="error" message={error} /> : null}
      {success ? <ProductMessage tone="success" message={success} /> : null}
      <FinanceMetrics totals={totals} isLoading={isLoading} />
      <ExpenseInsights expenses={visibleExpenses} categories={categories} isLoading={isLoading} />
      <ExpenseFilters startDate={startDate} endDate={endDate} category={category} source={source} search={search} sourceOptions={sourceOptions} resultCount={visibleExpenses.length} filtersChanged={filtersChanged} onStartDate={setStartDate} onEndDate={setEndDate} onCategory={setCategory} onSource={setSource} onSearch={setSearch} onClear={clearFilters} />
      <PremiumExpenseTable expenses={visibleExpenses} isLoading={isLoading} setupRequired={setupRequired} filtered={filtersChanged} onCreate={openCreate} onEdit={openEdit} onDelete={setDeleting} />
      {isFormOpen ? <TaxAwareExpenseDrawer form={form} editing={editing} isSaving={isSaving} error={error} onClose={closeDrawer} onChange={setForm} onSubmit={saveExpense} /> : null}
      {isFormOpen && form.category === "traffic" ? <div className="fixed bottom-36 right-6 z-[60] w-[calc(100%-3rem)] max-w-lg rounded-2xl border border-cyan/15 bg-[#071019]/95 p-3 shadow-panel backdrop-blur-xl"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.13em] text-cyan">Atribuição da campanha</p><div className="grid gap-2 sm:grid-cols-2"><select className="h-10 rounded-xl border border-white/[.1] bg-[#060a11] px-3 text-xs text-slate-200" value={expenseAccountId} onChange={(event) => { setExpenseAccountId(event.target.value); setForm((current) => ({ ...current, campaignId: null })); }}><option value="">Todas as contas</option>{adAccounts.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.name} · {item.platform}</option>)}</select><select className="h-10 rounded-xl border border-white/[.1] bg-[#060a11] px-3 text-xs text-slate-200" value={form.campaignId || ""} onChange={(event) => setForm((current) => ({ ...current, campaignId: event.target.value || null }))}><option value="">Sem campanha</option>{campaigns.filter((item) => !expenseAccountId || item.adAccountId === expenseAccountId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><p className="mt-2 text-[10px] text-slate-500">Usa esta despesa como investimento; nenhum lançamento adicional é criado.</p></div> : null}
      {isFormOpen ? <button type="button" onClick={() => { setCategoryError(null); setIsCategoryOpen(true); }} className="fixed bottom-20 right-6 z-[60] rounded-xl border border-money/25 bg-[#07110e] px-4 py-2.5 text-sm font-semibold text-money shadow-panel transition hover:bg-money/[.08]">+ Criar nova categoria</button> : null}
      {isCategoryOpen ? <div className="fixed inset-0 z-[70] grid place-items-center bg-black/70 p-4"><form onSubmit={createCategory} className="w-full max-w-sm rounded-2xl border border-white/[.1] bg-[#080d14] p-5 shadow-panel"><h2 className="text-lg font-semibold text-white">Criar nova categoria</h2><p className="mt-1 text-xs text-slate-500">Ela ficará disponível em novos lançamentos, filtros e análises.</p><label className="mt-5 block text-xs text-slate-400">Nome<input autoFocus value={categoryName} onChange={(event) => setCategoryName(event.target.value)} maxLength={60} className="mt-2 h-11 w-full rounded-xl border border-white/[.1] bg-black/20 px-3 text-sm text-white outline-none focus:border-money/40" required /></label>{categoryError ? <p className="mt-3 text-xs text-danger">{categoryError}</p> : null}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setIsCategoryOpen(false)} className="rounded-xl border border-white/[.1] px-4 py-2 text-sm text-slate-400">Cancelar</button><button type="submit" disabled={isSaving} className="rounded-xl bg-money px-4 py-2 text-sm font-semibold text-[#02130b] disabled:opacity-50">{isSaving ? "Criando..." : "Criar categoria"}</button></div></form></div> : null}
      {deleting ? <DeleteExpenseDialog expense={deleting} isSaving={isSaving} onCancel={() => setDeleting(null)} onConfirm={deleteExpense} /> : null}
    </div>
  );
}
