"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { initialMetaAdsTaxConfiguration, type Expense, type ExpenseCategory, type ExpenseInput, type ExpenseTaxItem } from "@/data/expense-types";
import {
  TaxAwareExpenseDrawer,
  ExpenseFilters,
  ExpenseInsights,
  ExpenseSetupNotice,
  PremiumExpenseTable,
  FinanceHeader,
  FinanceMetrics,
  DeleteExpenseDialog,
  ProductMessage
} from "@/modules/finance/components/expense-workspace";

const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => `${today().slice(0, 7)}-01`;

const emptyForm: ExpenseInput = {
  description: "",
  category: "traffic",
  amount: "",
  expenseDate: today(),
  source: "Meta Ads",
  notes: "",
  taxCalculationMode: "on_top",
  taxItems: initialMetaAdsTaxConfiguration.map((item) => ({ ...item, calculationBase: 0, amount: 0, calculationMode: "on_top", isAutoGenerated: true, enabled: true }))
};

function expenseTaxes(expense: Expense) {
  return (expense.taxItems || []).reduce((sum, item) => sum + item.amount, 0);
}

async function readJson(response: Response) {
  const text = await response.text();
  if (!text) return {};
  try {
    return JSON.parse(text) as Record<string, unknown>;
  } catch {
    return { error: "O servidor retornou uma resposta inválida." };
  }
}

function inclusiveDays(start: string, end: string) {
  const startTime = new Date(`${start}T12:00:00Z`).getTime();
  const endTime = new Date(`${end}T12:00:00Z`).getTime();
  if (!Number.isFinite(startTime) || !Number.isFinite(endTime) || endTime < startTime) return 1;
  return Math.floor((endTime - startTime) / 86400000) + 1;
}

export function ExpensesScreen() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [startDate, setStartDate] = useState(monthStart());
  const [endDate, setEndDate] = useState(today());
  const [category, setCategory] = useState<ExpenseCategory | "all">("all");
  const [source, setSource] = useState("all");
  const [search, setSearch] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [setupRequired, setSetupRequired] = useState(false);
  const [taxSetupRequired, setTaxSetupRequired] = useState(false);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [form, setForm] = useState<ExpenseInput>(emptyForm);
  const [editing, setEditing] = useState<Expense | null>(null);
  const [deleting, setDeleting] = useState<Expense | null>(null);
  const [drawerInitial, setDrawerInitial] = useState("");

  const loadExpenses = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ start: startDate, end: endDate });
      if (category !== "all") params.set("category", category);
      const response = await fetch(`/api/expenses?${params}`, { cache: "no-store", credentials: "include" });
      const payload = await readJson(response);
      if (!response.ok) throw new Error(String(payload.error || "Não foi possível carregar as despesas."));
      setExpenses(Array.isArray(payload.expenses) ? payload.expenses as Expense[] : []);
      setSetupRequired(Boolean(payload.setupRequired));
      setTaxSetupRequired(Boolean(payload.taxSetupRequired));
    } catch (loadError) {
      setExpenses([]);
      setError(loadError instanceof Error ? loadError.message : "Não foi possível carregar as despesas.");
    } finally {
      setIsLoading(false);
    }
  }, [startDate, endDate, category]);

  useEffect(() => { loadExpenses(); }, [loadExpenses]);
  useEffect(() => {
    if (!success) return;
    const timeout = window.setTimeout(() => setSuccess(null), 3500);
    return () => window.clearTimeout(timeout);
  }, [success]);

  const sourceOptions = useMemo(() => Array.from(new Set(expenses.map((item) => item.source).filter((item): item is string => Boolean(item)))).sort(), [expenses]);
  const visibleExpenses = useMemo(() => {
    const term = search.trim().toLocaleLowerCase("pt-BR");
    return expenses.filter((item) => {
      if (source !== "all" && item.source !== source) return false;
      if (term && !item.description.toLocaleLowerCase("pt-BR").includes(term)) return false;
      return true;
    });
  }, [expenses, search, source]);

  const totals = useMemo(() => {
    const total = visibleExpenses.reduce((sum, item) => sum + item.amount + expenseTaxes(item), 0);
    const traffic = visibleExpenses.filter((item) => item.category === "traffic").reduce((sum, item) => sum + item.amount, 0);
    const taxes = visibleExpenses.reduce((sum, item) => sum + expenseTaxes(item), 0);
    return { total, traffic, taxes, count: visibleExpenses.length, dailyAverage: total / inclusiveDays(startDate, endDate) };
  }, [visibleExpenses, startDate, endDate]);

  const filtersChanged = startDate !== monthStart() || endDate !== today() || category !== "all" || source !== "all" || Boolean(search.trim());
  const periodLabel = `${new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${startDate}T12:00:00Z`))} — ${new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(`${endDate}T12:00:00Z`))}`;

  function clearFilters() {
    setStartDate(monthStart());
    setEndDate(today());
    setCategory("all");
    setSource("all");
    setSearch("");
  }

  function openCreate() {
    setEditing(null);
    const nextForm = { ...emptyForm, expenseDate: today(), taxItems: emptyForm.taxItems?.map((item) => ({ ...item })) };
    setForm(nextForm);
    setDrawerInitial(JSON.stringify(nextForm));
    setIsFormOpen(true);
  }

  function openEdit(expense: Expense) {
    setEditing(expense);
    const linkedTaxes = expense.taxItems || [];
    const mode = linkedTaxes[0]?.calculationMode || "on_top";
    const configuredTaxes: ExpenseTaxItem[] = initialMetaAdsTaxConfiguration.map((initial) => {
      const saved = linkedTaxes.find((item) => item.taxCode === initial.taxCode);
      return saved ? { ...saved, enabled: true } : { ...initial, calculationBase: expense.amount, amount: 0, calculationMode: mode, isAutoGenerated: true, enabled: false };
    });
    const displayedAmount = mode === "included" ? expense.amount + linkedTaxes.reduce((sum, item) => sum + item.amount, 0) : expense.amount;
    const nextForm = { description: expense.description, category: expense.category, amount: String(displayedAmount), expenseDate: expense.expenseDate, source: expense.source || "", notes: expense.notes || "", taxCalculationMode: mode, taxItems: configuredTaxes } satisfies ExpenseInput;
    setForm(nextForm);
    setDrawerInitial(JSON.stringify(nextForm));
    setIsFormOpen(true);
  }

  function closeDrawer() {
    const dirty = JSON.stringify(form) !== drawerInitial;
    if (dirty && !window.confirm("Descartar as alterações desta despesa?")) return;
    setIsFormOpen(false);
    setEditing(null);
  }

  async function saveExpense(event: FormEvent) {
    event.preventDefault();
    setIsSaving(true);
    setError(null);
    try {
      const isMetaAds = form.category === "traffic" && form.source === "Meta Ads";
      const enabledTaxes = isMetaAds ? (form.taxItems || []).filter((item) => item.enabled !== false) : [];
      const enteredAmount = Number(String(form.amount).replace(",", "."));
      const rateTotal = enabledTaxes.reduce((sum, item) => sum + Number(item.ratePercent || 0), 0);
      const mediaAmount = form.taxCalculationMode === "included" ? enteredAmount / (1 + rateTotal / 100) : enteredAmount;
      const requestPayload = {
        ...form,
        amount: Math.round(mediaAmount * 100) / 100,
        taxItems: enabledTaxes.map((item) => ({ ...item, calculationBase: mediaAmount, amount: mediaAmount * (item.ratePercent / 100), calculationMode: form.taxCalculationMode || "on_top" }))
      };
      const response = await fetch(editing ? `/api/expenses?id=${editing.id}` : "/api/expenses", {
        method: editing ? "PATCH" : "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(requestPayload)
      });
      const responsePayload = await readJson(response);
      if (!response.ok) throw new Error(String(responsePayload.error || "Não foi possível salvar a despesa."));
      setIsFormOpen(false);
      setEditing(null);
      setSuccess(editing ? "Despesa atualizada com sucesso." : "Despesa registrada com sucesso.");
      await loadExpenses();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Não foi possível salvar a despesa.");
    } finally {
      setIsSaving(false);
    }
  }

  async function deleteExpense() {
    if (!deleting) return;
    setIsSaving(true);
    setError(null);
    try {
      const response = await fetch(`/api/expenses?id=${deleting.id}`, { method: "DELETE", credentials: "include" });
      const payload = await readJson(response);
      if (!response.ok) throw new Error(String(payload.error || "Não foi possível excluir a despesa."));
      setDeleting(null);
      setSuccess("Despesa excluída com sucesso.");
      await loadExpenses();
    } catch (deleteError) {
      setError(deleteError instanceof Error ? deleteError.message : "Não foi possível excluir a despesa.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="space-y-4 pb-10 pt-2">
      <FinanceHeader periodLabel={periodLabel} setupRequired={setupRequired} onCreate={openCreate} />
      {setupRequired ? <ExpenseSetupNotice /> : null}
      {taxSetupRequired ? <ProductMessage tone="error" message="A migration 023 precisa ser aplicada para ativar os tributos automáticos da Meta Ads." /> : null}
      {error ? <ProductMessage tone="error" message={error} /> : null}
      {success ? <ProductMessage tone="success" message={success} /> : null}
      <FinanceMetrics totals={totals} isLoading={isLoading} />
      <ExpenseInsights expenses={visibleExpenses} isLoading={isLoading} />
      <ExpenseFilters startDate={startDate} endDate={endDate} category={category} source={source} search={search} sourceOptions={sourceOptions} resultCount={visibleExpenses.length} filtersChanged={filtersChanged} onStartDate={setStartDate} onEndDate={setEndDate} onCategory={setCategory} onSource={setSource} onSearch={setSearch} onClear={clearFilters} />
      <PremiumExpenseTable expenses={visibleExpenses} isLoading={isLoading} setupRequired={setupRequired} filtered={filtersChanged} onCreate={openCreate} onEdit={openEdit} onDelete={setDeleting} />
      {isFormOpen ? <TaxAwareExpenseDrawer form={form} editing={editing} isSaving={isSaving} error={error} onClose={closeDrawer} onChange={setForm} onSubmit={saveExpense} /> : null}
      {deleting ? <DeleteExpenseDialog expense={deleting} isSaving={isSaving} onCancel={() => setDeleting(null)} onConfirm={deleteExpense} /> : null}
    </div>
  );
}
