"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, CircleDollarSign, HandCoins, Plus, UsersRound, X } from "lucide-react";
import type { Coproducer, SaleCoproducerObligation } from "@/data/participation-types";
import { brl, ProductMessage } from "@/modules/finance/components/expense-workspace";
import { cn } from "@/lib/utils";

type Tab = "pending" | "paid" | "coproducers";
const localToday = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
async function read(response: Response) { const text = await response.text(); try { return text ? JSON.parse(text) as Record<string, unknown> : {}; } catch { return {}; } }

export function ParticipationsScreen() {
  const [tab, setTab] = useState<Tab>("pending"); const [pendingItems, setPendingItems] = useState<SaleCoproducerObligation[]>([]); const [paidItems, setPaidItems] = useState<SaleCoproducerObligation[]>([]); const [coproducers, setCoproducers] = useState<Coproducer[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [paying, setPaying] = useState<SaleCoproducerObligation | null>(null); const [creating, setCreating] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [pendingResponse,paidResponse,c] = await Promise.all([fetch("/api/participations?status=pending", { cache:"no-store" }),fetch("/api/participations?status=paid", { cache:"no-store" }), fetch("/api/coproducers", { cache:"no-store" })]); const pendingPayload = await read(pendingResponse); const paidPayload = await read(paidResponse); const cp = await read(c); if (!pendingResponse.ok || !paidResponse.ok) throw new Error(String(pendingPayload.error || paidPayload.error || "Não foi possível carregar as participações.")); if (!c.ok) throw new Error(String(cp.error || "Não foi possível carregar os coprodutores.")); setPendingItems(Array.isArray(pendingPayload.participations) ? pendingPayload.participations as SaleCoproducerObligation[] : []); setPaidItems(Array.isArray(paidPayload.participations) ? paidPayload.participations as SaleCoproducerObligation[] : []); setCoproducers(Array.isArray(cp.coproducers) ? cp.coproducers as Coproducer[] : []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao carregar Participações."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const items = tab === "paid" ? paidItems : pendingItems; const currentMonth = localToday().slice(0,7); const pendingTotal = pendingItems.reduce((sum,item) => sum + item.amount,0); const paidTotal = paidItems.filter(item=>item.paidAt?.startsWith(currentMonth)).reduce((sum,item) => sum + item.amount,0); const activeCoproducers = coproducers.filter((item) => item.status === "active").length;
  async function pay(values: { amount: number; date: string }) { if (!paying) return; const response = await fetch(`/api/participations/${paying.id}/payment`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({confirmedAmount:values.amount,paidAt:values.date}) }); const payload = await read(response); if (!response.ok) { setError(String(payload.error || "Não foi possível confirmar o pagamento.")); return; } setPaying(null); setSuccess("Participação paga e despesa criada uma única vez."); await load(); }
  return <div className="space-y-5 pb-10 pt-2"><header className="luxury-surface kau-surgical-surface rounded-[28px] px-5 py-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-money">Financeiro / Participações</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-white">Participações</h1><p className="mt-1 text-sm text-slate-400">Coprodutores, regras econômicas e pagamentos vinculados às vendas.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Aguardando confirmação",String(pendingItems.length)],["Valor pendente",brl(pendingTotal)],["Pago no mês",brl(paidTotal)],["Coprodutores ativos",String(activeCoproducers)]].map(([label,value])=><div key={label} className="kau-surgical-card rounded-[22px] border border-white/[.08] bg-[#081019]/82 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold tabular-nums text-white">{loading?"—":value}</p></div>)}</section>
    <nav className="inline-flex flex-wrap rounded-2xl border border-white/[.08] bg-[#070c13]/80 p-1">{[["pending","Aguardando confirmação"],["paid","Concluídas"],["coproducers","Coprodutores"]].map(([value,label])=><button key={value} onClick={()=>setTab(value as Tab)} className={cn("rounded-xl px-4 py-2.5 text-sm font-semibold",tab===value?"bg-money/[.1] text-money":"text-slate-500")}>{label}</button>)}</nav>
    {error?<ProductMessage tone="error" message={error}/>:null}{success?<ProductMessage tone="success" message={success}/>:null}
    {tab === "coproducers" ? <CoproducerPanel items={coproducers} loading={loading} onNew={()=>setCreating(true)} /> : <ParticipationList items={items} loading={loading} paid={tab==="paid"} onPay={setPaying}/>} {paying?<PaymentModal item={paying} onClose={()=>setPaying(null)} onPay={pay}/>:null}{creating?<CoproducerModal onClose={()=>setCreating(false)} onSaved={async()=>{setCreating(false);await load();}}/>:null}
  </div>;
}

function ParticipationList({items,loading,paid,onPay}:{items:SaleCoproducerObligation[];loading:boolean;paid:boolean;onPay:(item:SaleCoproducerObligation)=>void}) { return <section className="overflow-hidden rounded-[26px] border border-white/[.08] bg-[#071019]/78">{loading?<p className="p-8 text-sm text-slate-500">Carregando…</p>:items.length?<div className="divide-y divide-white/[.06]">{items.map(item=><article key={item.id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_.8fr_auto] lg:items-center"><div><p className="text-base font-semibold text-white">{item.coproducerName}</p><p className="mt-1 text-xs text-slate-500">{item.sale.customerName} · #{item.saleId.slice(0,8).toUpperCase()}</p><p className="mt-1 text-xs text-slate-500">{item.sale.productName}</p></div><div><p className="text-[10px] uppercase tracking-[.1em] text-slate-600">Regra usada</p><p className="mt-1 text-sm text-slate-300">{item.calculationType==="percent"?`${item.percent}% da Receita da Operação`:`${brl(item.fixedAmount||0)} por venda`}</p><p className="mt-1 text-xs text-slate-500">Base {brl(item.basisAmount)}</p></div><div><p className="text-[10px] uppercase tracking-[.1em] text-slate-600">Participação</p><p className="mt-1 text-xl font-semibold tabular-nums text-white">{brl(item.amount)}</p></div>{paid?<span className="inline-flex items-center gap-1 text-xs font-semibold text-money"><CheckCircle2 size={14}/>Paga</span>:<button onClick={()=>onPay(item)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-money px-3 text-xs font-semibold text-[#02130b]"><CircleDollarSign size={14}/>Confirmar pagamento</button>}</article>)}</div>:<p className="p-12 text-center text-sm text-slate-500">Nenhuma participação nesta visão.</p>}</section>; }
function CoproducerPanel({items,loading,onNew}:{items:Coproducer[];loading:boolean;onNew:()=>void}) { return <section className="rounded-[26px] border border-white/[.08] bg-[#071019]/78 p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-white">Coprodutores</h2><p className="mt-1 text-xs text-slate-500">Cadastro financeiro global de participantes.</p></div><button onClick={onNew} className="inline-flex h-10 items-center gap-2 rounded-xl bg-money px-3 text-xs font-semibold text-[#02130b]"><Plus size={14}/>Adicionar coprodutor</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{loading?<p className="text-sm text-slate-500">Carregando…</p>:items.map(item=><div key={item.id} className="rounded-2xl border border-white/[.07] bg-white/[.018] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-300/[.08] text-violet-200"><UsersRound size={17}/></span><div><p className="font-semibold text-white">{item.name}</p><p className="text-xs text-slate-500">{item.status==="active"?"Ativo":"Inativo"}{item.email?` · ${item.email}`:""}</p></div></div></div>)}</div></section>; }
function PaymentModal({item,onClose,onPay}:{item:SaleCoproducerObligation;onClose:()=>void;onPay:(v:{amount:number;date:string})=>void}) { const [amount,setAmount]=useState(String(item.amount.toFixed(2)).replace(".",",")); const [date,setDate]=useState(localToday()); return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4"><form onSubmit={e=>{e.preventDefault();onPay({amount:Number(amount.replace(",",".")),date});}} className="w-full max-w-lg rounded-[26px] border border-white/[.1] bg-[#081019] p-5"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.13em] text-money">Participação</p><h2 className="mt-1 text-xl font-semibold text-white">Confirmar pagamento</h2></div><button type="button" onClick={onClose}><X size={18}/></button></div><div className="mt-5 rounded-2xl bg-white/[.025] p-4"><p className="font-semibold text-white">{item.coproducerName}</p><p className="mt-1 text-xs text-slate-500">{item.sale.customerName} · {item.sale.productName}</p><p className="mt-3 text-sm text-slate-300">Base: {brl(item.basisAmount)} · Calculado: {brl(item.amount)}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">Valor confirmado<input value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/[.1] bg-black/20 px-3 text-white"/></label><label className="text-xs text-slate-400">Data real do pagamento<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/[.1] bg-black/20 px-3 text-white"/></label></div><button className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-money font-semibold text-[#02130b]"><HandCoins size={16}/>Confirmar pagamento</button></form></div>; }
function CoproducerModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}) { const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();const response=await fetch("/api/coproducers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email})});const payload=await read(response);if(!response.ok){setError(String(payload.error||"Não foi possível cadastrar."));return;}onSaved();} return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-[26px] border border-white/[.1] bg-[#081019] p-5"><div className="flex justify-between"><h2 className="text-xl font-semibold text-white">Adicionar coprodutor</h2><button type="button" onClick={onClose}><X size={18}/></button></div><label className="mt-5 block text-xs text-slate-400">Nome<input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 h-11 w-full rounded-xl border border-white/[.1] bg-black/20 px-3 text-white"/></label><label className="mt-4 block text-xs text-slate-400">E-mail opcional<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/[.1] bg-black/20 px-3 text-white"/></label>{error?<p className="mt-3 text-xs text-danger">{error}</p>:null}<button className="mt-5 h-11 w-full rounded-xl bg-money font-semibold text-[#02130b]">Cadastrar</button></form></div>; }
