"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CalendarDays, Handshake, Plus, UserRoundCheck } from "lucide-react";
import type { Coproducer, CoproducerRole, ProductCoproducerRule } from "@/data/participation-types";
import { brl, localDateKey, productInputClass, productPrimaryButtonClass, readJson } from "@/modules/products/product-ui";

const roleLabels: Record<CoproducerRole,string> = { coproducer:"Coprodutor",partner:"Sócio",producer:"Produtor" };
export function ProductCoproducers({productId,onCount}:{productId:string;onCount:(count:number)=>void}) {
  const [rules,setRules]=useState<ProductCoproducerRule[]>([]); const [people,setPeople]=useState<Coproducer[]>([]); const [open,setOpen]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{const [r,c]=await Promise.all([fetch(`/api/products/${productId}/coproducers`,{cache:"no-store"}),fetch("/api/coproducers",{cache:"no-store"})]);const rp=await readJson(r) as {rules?:ProductCoproducerRule[];error?:string};const cp=await readJson(c) as {coproducers?:Coproducer[];error?:string};if(!r.ok||!c.ok){setError(String(rp.error||cp.error||"Não foi possível carregar coprodutores."));return;}const next=rp.rules||[];setRules(next);setPeople(cp.coproducers||[]);onCount(next.filter(item=>item.status==="active").length);},[productId,onCount]);
  useEffect(()=>{void load();},[load]);
  async function end(rule:ProductCoproducerRule){const response=await fetch(`/api/products/${productId}/coproducers`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ruleId:rule.id,effectiveTo:localDateKey()})});if(!response.ok){const p=await readJson(response);setError(String((p as {error?:string}).error||"Não foi possível encerrar a regra."));return;}await load();}
  return <section className="luxury-surface kau-surgical-surface rounded-[28px] p-5 md:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold text-white">Coprodutores do produto</h2><p className="mt-1 text-sm text-slate-400">Regras com vigência e base financeira explícita.</p></div><button onClick={()=>setOpen(true)} className={productPrimaryButtonClass}><Plus size={15}/>Adicionar coprodutor</button></div>{error?<p className="mt-4 text-xs text-danger">{error}</p>:null}<div className="mt-5 space-y-3">{rules.length?rules.map(rule=><article key={rule.id} className="rounded-[22px] border border-white/[.07] bg-[#07121b]/76 p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-300/[.08] text-violet-200"><Handshake size={18}/></span><div><p className="font-semibold text-white">{rule.coproducer?.name||"Coprodutor"}</p><p className="mt-1 text-xs text-slate-500">{roleLabels[rule.role]} · {rule.calculationType==="percent"?`${rule.percent}% da Receita da Operação`:`${brl(rule.fixedAmount||0)} por venda`}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-600"><CalendarDays size={11}/>Vigente desde {rule.effectiveFrom}</p></div></div>{rule.status==="active"?<button onClick={()=>void end(rule)} className="rounded-xl border border-white/[.09] px-3 py-2 text-xs text-slate-400">Encerrar vigência</button>:<span className="text-xs text-slate-600">Encerrada em {rule.effectiveTo}</span>}</div></article>):<div className="rounded-2xl border border-dashed border-white/[.09] p-10 text-center"><UserRoundCheck size={22} className="mx-auto text-money"/><p className="mt-3 text-sm font-semibold text-white">Produto sem coprodutor</p><p className="mt-1 text-xs text-slate-500">O produto e suas vendas continuam funcionando normalmente.</p></div>}</div>{open?<RuleModal productId={productId} people={people.filter(p=>p.status==="active")} onClose={()=>setOpen(false)} onSaved={async()=>{setOpen(false);await load();}}/>:null}</section>;
}
function RuleModal({productId,people,onClose,onSaved}:{productId:string;people:Coproducer[];onClose:()=>void;onSaved:()=>void}){const [person,setPerson]=useState("");const [role,setRole]=useState<CoproducerRole>("coproducer");const [type,setType]=useState<"percent"|"fixed">("percent");const [value,setValue]=useState("");const [date,setDate]=useState(localDateKey());const [error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();const response=await fetch(`/api/products/${productId}/coproducers`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({coproducerId:person,role,calculationType:type,[type==="percent"?"percent":"fixedAmount"]:value,effectiveFrom:date})});const payload=await readJson(response) as {error?:string};if(!response.ok){setError(String(payload.error||"Não foi possível criar a regra."));return;}onSaved();}return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-[26px] border border-white/[.1] bg-[#081019] p-5"><h2 className="text-xl font-semibold text-white">Adicionar coprodutor</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs text-slate-400 sm:col-span-2">Coprodutor<select value={person} onChange={e=>setPerson(e.target.value)} required className={`mt-2 ${productInputClass}`}><option value="">Selecione</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs text-slate-400">Papel<select value={role} onChange={e=>setRole(e.target.value as CoproducerRole)} className={`mt-2 ${productInputClass}`}><option value="coproducer">Coprodutor</option><option value="partner">Sócio</option><option value="producer">Produtor</option></select></label><label className="text-xs text-slate-400">Tipo<select value={type} onChange={e=>setType(e.target.value as "percent"|"fixed")} className={`mt-2 ${productInputClass}`}><option value="percent">Percentual</option><option value="fixed">Valor fixo por venda</option></select></label><label className="text-xs text-slate-400">{type==="percent"?"Percentual da Receita da Operação":"Valor fixo"}<input value={value} onChange={e=>setValue(e.target.value)} required className={`mt-2 ${productInputClass}`}/></label><label className="text-xs text-slate-400">Vigência inicial<input type="date" value={date} onChange={e=>setDate(e.target.value)} required className={`mt-2 ${productInputClass}`}/></label></div><p className="mt-3 text-[11px] text-slate-500">A base percentual é operation_commission_amount. Vendas antigas preservam seus snapshots.</p>{error?<p className="mt-3 text-xs text-danger">{error}</p>:null}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-white/[.1] px-4 py-2 text-sm text-slate-400">Cancelar</button><button className={productPrimaryButtonClass}>Criar regra</button></div></form></div>}
