export const expenseCategories: string[] = ["traffic", "tools", "team", "taxes", "guarantees", "products", "shipping", "coproducers", "other"];

export type SystemExpenseCategory = "traffic" | "tools" | "team" | "taxes" | "guarantees" | "products" | "shipping" | "coproducers" | "other";
export type ExpenseCategory = string;

export const expenseCategoryLabels: Record<string, string> = {
  traffic: "Tráfego",
  tools: "Ferramentas",
  team: "Equipe",
  taxes: "Impostos",
  guarantees: "Garantias",
  products: "Produto / Fábrica",
  shipping: "Frete / Logística",
  coproducers: "Coprodutores",
  other: "Outros"
};

export type ExpenseCategoryDefinition = {
  id: string;
  name: string;
  slug: string;
  isSystem: boolean;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export const fallbackExpenseCategoryDefinitions: ExpenseCategoryDefinition[] = expenseCategories.map((slug) => ({
  id: slug,
  name: expenseCategoryLabels[slug],
  slug,
  isSystem: true,
  isActive: true
}));

export function syncExpenseCategoryDefinitions(definitions: ExpenseCategoryDefinition[]) {
  expenseCategories.splice(0, expenseCategories.length, ...definitions.filter((item) => item.isActive).map((item) => item.slug));
  definitions.forEach((item) => { expenseCategoryLabels[item.slug] = item.name; });
}

export function expenseCategoryName(category: string, definitions: ExpenseCategoryDefinition[] = []) {
  return definitions.find((item) => item.slug === category)?.name
    || expenseCategoryLabels[category as SystemExpenseCategory]
    || category;
}

export const trafficSources = ["Meta Ads", "Google Ads", "TikTok Ads", "Kwai Ads", "Outro"] as const;

export type TaxCalculationMode = "on_top" | "included";

export type ExpenseTaxItem = {
  id?: string;
  taxName: string;
  taxCode: string;
  ratePercent: number;
  calculationBase: number;
  amount: number;
  calculationMode: TaxCalculationMode;
  isAutoGenerated: boolean;
  enabled?: boolean;
  createdAt?: string;
};

// Configuração inicial isolada para futura substituição por Configurações → Financeiro.
// Os percentuais são copiados para cada lançamento e permanecem editáveis no formulário.
export const initialMetaAdsTaxConfiguration: Array<Pick<ExpenseTaxItem, "taxName" | "taxCode" | "ratePercent">> = [
  { taxName: "ISS", taxCode: "ISS", ratePercent: 2.9 },
  { taxName: "PIS/COFINS", taxCode: "PIS_COFINS", ratePercent: 9.25 }
];

export type Expense = {
  id: string;
  description: string;
  category: ExpenseCategory;
  amount: number;
  expenseDate: string;
  source?: string;
  notes?: string;
  createdBy: string;
  createdAt?: string;
  updatedAt?: string;
  taxItems?: ExpenseTaxItem[];
  managedByGuarantee?: boolean;
  guaranteeId?: string;
  managedByManualSaleCost?: boolean;
  manualSaleCostObligationId?: string;
  managedByParticipation?: boolean;
  participationId?: string;
  campaignId?: string;
};

export type ExpenseInput = {
  description: string;
  category: ExpenseCategory;
  amount: number | string;
  expenseDate: string;
  source?: string;
  notes?: string;
  taxItems?: ExpenseTaxItem[];
  taxCalculationMode?: TaxCalculationMode;
  campaignId?: string | null;
};
