export const expenseCategories = ["traffic", "tools", "team", "taxes", "guarantees", "other"] as const;

export type ExpenseCategory = (typeof expenseCategories)[number];

export const expenseCategoryLabels: Record<ExpenseCategory, string> = {
  traffic: "Tráfego",
  tools: "Ferramentas",
  team: "Equipe",
  taxes: "Impostos",
  guarantees: "Garantias",
  other: "Outros"
};

export const trafficSources = ["Meta Ads", "Google Ads", "TikTok Ads", "Kwai Ads", "Outro"] as const;

export type TaxCalculationMode = "on_top" | "included";

export type ExpenseTaxItem = {
  id?: string;
  taxName: string;
  taxCode: string;
  ratePercent: number;
  calculationBase: number;
  amount: number;
  calculationMode: TaxCalculationMode;
  isAutoGenerated: boolean;
  enabled?: boolean;
  createdAt?: string;
};

// Configuração inicial isolada para futura substituição por Configurações → Financeiro.
// Os percentuais são copiados para cada lançamento e permanecem editáveis no formulário.
export const initialMetaAdsTaxConfiguration: Array<Pick<ExpenseTaxItem, "taxName" | "taxCode" | "ratePercent">> = [
  { taxName: "ISS", taxCode: "ISS", ratePercent: 2.9 },
  { taxName: "PIS/COFINS", taxCode: "PIS_COFINS", ratePercent: 9.25 }
];

export type Expense = {
  id: string;
  description: string;
  category: ExpenseCategory;
  amount: number;
  expenseDate: string;
  source?: string;
  notes?: string;
  createdBy: string;
  createdAt?: string;
  updatedAt?: string;
  taxItems?: ExpenseTaxItem[];
  managedByGuarantee?: boolean;
  guaranteeId?: string;
};

export type ExpenseInput = {
  description: string;
  category: ExpenseCategory;
  amount: number | string;
  expenseDate: string;
  source?: string;
  notes?: string;
  taxItems?: ExpenseTaxItem[];
  taxCalculationMode?: TaxCalculationMode;
};
